#!/usr/bin/env python
"""
Extracts keys from JSON records and outputs honest-to-goodness TSV.
"""

from __future__ import print_function

import sys
import re
import json
import argparse
from functools import reduce

import tsvutil
tsvutil.fix_stdio()


def stringify(value):
    if not isinstance(value, basestring):
        value = str(value)
    elif isinstance(value, unicode):
        value = value.encode('utf-8')
    return tsvutil.WHITESPACE.sub(' ', value)


parser = argparse.ArgumentParser(prog='json2tsv', description=__doc__)
parser.add_argument('-H', '--no-header', action='store_false', dest='header')
parser.add_argument('-f', metavar='list', action='append', dest='fields')
args = parser.parse_args()


fields = reduce(lambda x, y: x.extend(y) or x,
                (l.split(',') for l in args.fields), [])

if args.header:
    print('\t'.join(fields))

for line in sys.stdin:
    record = json.loads(line)
    values = [(stringify(record[k]) if k in record else '')
              for k in fields]
    print('\t'.join(values))
